schema_version = "1.0.0"

id = "colorful_connections"
version = "1.0.0"
name = "彩色连线"
tagline = "为Blender节点编辑器提供彩色连线功能，增强节点编辑体验"
maintainer = "Blender超级技术交流社"
type = "add-on"

website = "https://www.blender.org"

tags = ["Node", "UI"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]